version: '3'

silent: true

tasks:
  world:
    desc: run local development tasks
    cmds:
      - task: format
      - task: ci
      - task: vendor

  ci:
    desc: run validation tasks
    cmds:
      - task: lint
      - task: workflow-test
      - task: build

  format:
    desc: format sources
    cmds: [ go fmt ./... ]

  lint:
    desc: run linter
    cmds: [ golangci-lint run ./... ]

  workflow-test:
    desc: workflow test
    dir: test/
    cmds:
      - go clean -testcache
      - go test -v ./...

  build:
    deps: [ clean ]
    desc: build binaries
    cmds:
      - mkdir out/
      - go build -o out/tcr cmd/tcr/main.go

  clean: rm -rf out/

  vendor:
    cmds:
      - go mod verify
      - go mod tidy
      - go mod vendor

  install:
    desc: install binary into "$HOME/bin"
    deps: [ build ]
    cmds: [ cp out/tcr "$HOME/bin/tcr" ]

  default:
    cmds: [ task: world ]


  set-default-git-author:
    desc: set default author for tests running on ci
    cmds:
      - git config --global user.name "ci-user"
      - git config --global user.email "ci@user.tld"