version: '3'

silent: true

tasks:
  world:
    desc: run all validation tasks
    cmds:
      - task: format
      - task: lint
      - task: workflow-test
      - task: build
      - task: vendor

  format:
    desc: format sources
    cmds: [ go fmt ./... ]

  lint:
    desc: run linter
    cmds: [ golangci-lint run ./... ]

  workflow-test:
    desc: workflow test
    dir: test/
    cmds:
      - go clean -testcache
      - go test -v ./...

  build:
    deps: [ clean ]
    desc: build binaries
    cmds:
      - mkdir out/
      - go build -o out/cli cmd/cli/main.go

  vendor:
    cmds:
      - go mod verify
      - go mod tidy
      - go mod vendor

  install:
    desc: install binary into "$HOME/bin"
    deps: [ build ]
    cmds: [ cp out/cli "$HOME/bin/tcr" ]

  clean: rm -rf out/

  default:
    cmds: [ task: world ]
